#!/bin/sh
# Run the given command after the current song.
# Copyright 2010-2012 Tom Vincent <http://tlvince.com/contact>

[ "$1" ] || { echo "usage: $0 cmd" && exit 1; }

current="$(mpc current)"

while [ "$(mpc current)" == "$current" ]; do
  mpc idle player >/dev/null 2>&1
done

"$@"
